title: Edwin Moradian
logo: /assets/img/old-school-pixel.jpg
description: Hi, my name is Edwin Moradian. I'm a developer with a background in physics. I love programming, traveling, and making a difference where I can. In the last three years, I've primarily focused in the web development space and have worked with many diverse teams remotely from all parts of the globe. If you need a project built or have a job opportunity, please contact me or check out some of my recent projects.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
